#!/bin/bash
# ══════════════════════════════════════════════
# LocoBase — Menu-Driven Installer
# Usage: sudo -E bash install.sh
# ══════════════════════════════════════════════
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/config.env"

# ── Colors ──
C='\033[1;36m'    # cyan
G='\033[1;32m'    # green
Y='\033[1;33m'    # yellow
RED='\033[1;31m'  # red
DIM='\033[2m'     # dim
R='\033[0m'       # reset

step() { echo -e "\n${C}══════════════════════════════════════════════${R}"; echo -e "${C}  $1${R}"; echo -e "${C}══════════════════════════════════════════════${R}"; }
ok()   { echo -e "  ${G}✓${R} $1"; }
skip() { echo -e "  - $1 (skipped)"; }
warn() { echo -e "  ${Y}!${R} $1"; }

# ── Must run as root ──
if [ "$EUID" -ne 0 ]; then
    echo "Please run with: sudo -E bash install.sh"
    exit 1
fi

export SCRIPT_DIR

# ── Machine Lookup Table ──
KNOWN_MACHINES=(burro cerebro colmena hormiga mesa puente pulpo tortuga)

declare -A MACHINE_EMOJI_MAP=(
    [burro]="🫏"
    [cerebro]="🧠"
    [colmena]="🐝"
    [hormiga]="🐜"
    [mesa]="🪑"
    [puente]="🌉"
    [pulpo]="🐙"
    [tortuga]="🐢"
)

declare -A MACHINE_LABEL=(
    [burro]="burro (donkey)"
    [cerebro]="cerebro (brain)"
    [colmena]="colmena (beehive)"
    [hormiga]="hormiga (ant)"
    [mesa]="mesa (table)"
    [puente]="puente (bridge)"
    [pulpo]="pulpo (octopus)"
    [tortuga]="tortuga (turtle)"
)

# ══════════════════════════════════════════════
# Machine Selection
# ══════════════════════════════════════════════
select_machine() {
    echo -e "\n${C}══════════════════════════════════════════════${R}"
    echo -e "${C}  Select Machine${R}"
    echo -e "${C}══════════════════════════════════════════════${R}"
    echo ""

    local i=1
    for m in "${KNOWN_MACHINES[@]}"; do
        echo -e "  ${G}${i})${R} ${MACHINE_LABEL[$m]}  ${MACHINE_EMOJI_MAP[$m]}"
        ((i++))
    done
    echo -e "  ${G}${i})${R} Custom machine name"
    echo ""

    local choice
    read -rp "  Select [1-${i}]: " choice

    if [[ "$choice" =~ ^[0-9]+$ ]] && [ "$choice" -ge 1 ] && [ "$choice" -le "${#KNOWN_MACHINES[@]}" ]; then
        MACHINE_NAME="${KNOWN_MACHINES[$((choice-1))]}"
        PROMPT_EMOJI="${MACHINE_EMOJI_MAP[$MACHINE_NAME]}"
    elif [[ "$choice" == "$i" ]]; then
        read -rp "  Enter machine name: " MACHINE_NAME
        if [ -z "$MACHINE_NAME" ]; then
            echo "  No name entered. Aborting."
            exit 1
        fi
        # Check if there's an art folder for this name
        if [ -d "$SCRIPT_DIR/ascii-art/${MACHINE_NAME,,}" ]; then
            echo -e "  ${G}✓${R} Found art folder: ascii-art/${MACHINE_NAME,,}/"
        else
            echo -e "  ${DIM}  No art folder found at ascii-art/${MACHINE_NAME,,}/ — MOTD will install without art.${R}"
            echo -e "  ${DIM}  You can add art later and re-run MOTD setup from the Post-Install menu.${R}"
        fi
        read -rp "  Enter emoji (Enter to skip): " PROMPT_EMOJI
        PROMPT_EMOJI="${PROMPT_EMOJI:-🖥️}"
    else
        echo "  Invalid selection."
        exit 1
    fi

    MACHINE_NAME="${MACHINE_NAME,,}"

    # Save selection
    cat > "$SCRIPT_DIR/.machine" <<EOF
# Machine identity — auto-generated by install.sh
# To change, re-run install.sh or edit this file.
MACHINE_NAME="$MACHINE_NAME"
PROMPT_EMOJI="$PROMPT_EMOJI"
EOF

    ok "Machine set: ${MACHINE_NAME} ${PROMPT_EMOJI}"
}

# ══════════════════════════════════════════════
# Workflow: Fresh Install / Fix Drift
# ══════════════════════════════════════════════
run_install() {
    export MACHINE_NAME SETUP_USER PROMPT_EMOJI
    USER_HOME=$(eval echo "~$SETUP_USER")

    # Temporary NOPASSWD sudo for unattended script execution
    step "Setting up temporary NOPASSWD sudo"
    echo "$SETUP_USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/${SETUP_USER}-nopasswd
    chmod 440 /etc/sudoers.d/${SETUP_USER}-nopasswd
    ok "NOPASSWD sudo enabled (removed at end or manually: sudo rm /etc/sudoers.d/${SETUP_USER}-nopasswd)"

    step "Installing packages"
    bash "$SCRIPT_DIR/scripts/01-packages.sh"

    step "NVIDIA drivers"
    if [ "$NVIDIA_ENABLE" = true ]; then
        bash "$SCRIPT_DIR/scripts/02-nvidia.sh"
    else
        skip "NVIDIA"
    fi

    step "AI stack (CUDA, Ollama, Docker, Node.js, HF CLI)"
    bash "$SCRIPT_DIR/scripts/10-ai-stack.sh"

    step "Plymouth boot splash"
    if [ "$PLYMOUTH_ENABLE" = true ]; then
        bash "$SCRIPT_DIR/scripts/03-plymouth.sh"
    else
        skip "Plymouth"
    fi

    step "MOTD"
    if [ "$MOTD_ENABLE" = true ]; then
        bash "$SCRIPT_DIR/scripts/04-motd.sh"
    else
        skip "MOTD"
    fi

    step "GRUB splash config"
    bash "$SCRIPT_DIR/scripts/05-grub.sh"

    step "Autologin"
    if [ "$AUTOLOGIN_ENABLE" = true ]; then
        bash "$SCRIPT_DIR/scripts/06-autologin.sh"
    else
        skip "Autologin"
    fi

    step "tmux dashboard"
    if [ "$DASHBOARD_ENABLE" = true ]; then
        bash "$SCRIPT_DIR/scripts/07-dashboard.sh"
    else
        skip "Dashboard"
    fi

    step "Bash prompt"
    bash "$SCRIPT_DIR/scripts/08-prompt.sh"

    step "Hardening"
    bash "$SCRIPT_DIR/scripts/09-harden.sh"

    step "SETUP COMPLETE"
    echo ""
    echo "  Machine: $MACHINE_NAME $PROMPT_EMOJI"
    echo "  User:    $SETUP_USER"
    echo ""
    echo "  Next steps:"
    echo "    1. Reboot to verify Plymouth + autologin + dashboard"
    echo "    2. Run post-install setup (option 4) for GitHub, Claude Code, fan curves, etc."
    echo "    3. After verifying, remove NOPASSWD sudo:"
    echo "       sudo rm /etc/sudoers.d/${SETUP_USER}-nopasswd"
    echo ""
}

# ══════════════════════════════════════════════
# Workflow: Full Reset
# ══════════════════════════════════════════════
run_reset() {
    export MACHINE_NAME SETUP_USER PROMPT_EMOJI
    bash "$SCRIPT_DIR/reset.sh"
}

# ══════════════════════════════════════════════
# Workflow: Rename Machine
# ══════════════════════════════════════════════
run_rename() {
    local OLD_NAME="${MACHINE_NAME,,}"
    USER_HOME=$(eval echo "~$SETUP_USER")

    echo -e "\n${C}══════════════════════════════════════════════${R}"
    echo -e "${C}  Rename Machine${R}"
    echo -e "${C}══════════════════════════════════════════════${R}"
    echo ""
    echo -e "  Current name: ${G}${OLD_NAME}${R} ${PROMPT_EMOJI}"
    echo ""
    echo -e "  This will:"
    echo -e "    1. Remove name-specific files for '${OLD_NAME}'"
    echo -e "    2. Prompt for a new machine name"
    echo -e "    3. Re-run config scripts (plymouth, motd, grub, etc.)"
    echo ""
    echo -e "  ${G}Safe:${R} Does NOT touch packages, services, Docker, or running workloads."
    echo ""

    read -rp "  Proceed? [y/N]: " confirm
    if [[ ! "$confirm" =~ ^[Yy] ]]; then
        echo "  Aborted."
        return
    fi

    # ── Remove old name-specific artifacts ──
    step "Removing old artifacts for '${OLD_NAME}'"

    # Plymouth theme directory
    if [ -d "/usr/share/plymouth/themes/${OLD_NAME}" ]; then
        update-alternatives --remove default.plymouth \
            "/usr/share/plymouth/themes/${OLD_NAME}/${OLD_NAME}.plymouth" 2>/dev/null || true
        rm -rf "/usr/share/plymouth/themes/${OLD_NAME}"
        ok "Removed Plymouth theme '${OLD_NAME}'"
    else
        skip "Plymouth theme"
    fi

    # MOTD script
    if [ -f "/etc/update-motd.d/01-${OLD_NAME}" ]; then
        rm -f "/etc/update-motd.d/01-${OLD_NAME}"
        ok "Removed /etc/update-motd.d/01-${OLD_NAME}"
    else
        skip "MOTD script"
    fi

    # Dashboard script
    if [ -f "${USER_HOME}/${OLD_NAME}-dashboard.sh" ]; then
        rm -f "${USER_HOME}/${OLD_NAME}-dashboard.sh"
        ok "Removed ${OLD_NAME}-dashboard.sh"
    else
        skip "Dashboard script"
    fi

    # Dashboard hook in .bash_profile
    if [ -f "${USER_HOME}/.bash_profile" ] && grep -q "Auto-start ${OLD_NAME} dashboard" "${USER_HOME}/.bash_profile"; then
        sed -i "/# Auto-start ${OLD_NAME} dashboard/,/^fi$/d" "${USER_HOME}/.bash_profile"
        sed -i '/^$/N;/^\n$/d' "${USER_HOME}/.bash_profile"
        ok "Removed dashboard hook from .bash_profile"
    else
        skip "Dashboard hook"
    fi

    # ── Select new machine name ──
    select_machine

    # ── Re-run config scripts with new name ──
    export MACHINE_NAME SETUP_USER PROMPT_EMOJI

    step "Plymouth boot splash"
    if [ "$PLYMOUTH_ENABLE" = true ]; then
        bash "$SCRIPT_DIR/scripts/03-plymouth.sh"
    else
        skip "Plymouth"
    fi

    step "MOTD"
    if [ "$MOTD_ENABLE" = true ]; then
        bash "$SCRIPT_DIR/scripts/04-motd.sh"
    else
        skip "MOTD"
    fi

    step "GRUB splash config"
    bash "$SCRIPT_DIR/scripts/05-grub.sh"

    step "Autologin"
    if [ "$AUTOLOGIN_ENABLE" = true ]; then
        bash "$SCRIPT_DIR/scripts/06-autologin.sh"
    else
        skip "Autologin"
    fi

    step "tmux dashboard"
    if [ "$DASHBOARD_ENABLE" = true ]; then
        bash "$SCRIPT_DIR/scripts/07-dashboard.sh"
    else
        skip "Dashboard"
    fi

    step "Bash prompt"
    bash "$SCRIPT_DIR/scripts/08-prompt.sh"

    step "Hardening"
    bash "$SCRIPT_DIR/scripts/09-harden.sh"

    step "RENAME COMPLETE"
    echo ""
    echo "  Renamed: ${OLD_NAME} → ${MACHINE_NAME} ${PROMPT_EMOJI}"
    echo ""
    echo "  Reboot to verify Plymouth + MOTD + dashboard."
    echo ""
}

# ══════════════════════════════════════════════
# Workflow: Run Individual Script
# ══════════════════════════════════════════════
run_individual() {
    export MACHINE_NAME SETUP_USER PROMPT_EMOJI

    echo -e "\n${C}══════════════════════════════════════════════${R}"
    echo -e "${C}  Run Individual Script${R}"
    echo -e "${C}══════════════════════════════════════════════${R}"
    echo ""
    echo -e "  ${G} 1)${R} 01-packages.sh     — Install all tools"
    echo -e "  ${G} 2)${R} 02-nvidia.sh       — NVIDIA drivers"
    echo -e "  ${G} 3)${R} 03-plymouth.sh     — Boot splash"
    echo -e "  ${G} 4)${R} 04-motd.sh         — Custom MOTD"
    echo -e "  ${G} 5)${R} 05-grub.sh         — GRUB splash config"
    echo -e "  ${G} 6)${R} 06-autologin.sh    — TTY autologin"
    echo -e "  ${G} 7)${R} 07-dashboard.sh    — tmux dashboard"
    echo -e "  ${G} 8)${R} 08-prompt.sh       — Bash prompt"
    echo -e "  ${G} 9)${R} 09-harden.sh       — UFW + fail2ban"
    echo -e "  ${G}10)${R} 10-ai-stack.sh     — CUDA + Ollama + Docker + Node.js + HF CLI"
    echo -e "  ${G} 0)${R} Back to main menu"
    echo ""

    local SCRIPTS=(
        "scripts/01-packages.sh"
        "scripts/02-nvidia.sh"
        "scripts/03-plymouth.sh"
        "scripts/04-motd.sh"
        "scripts/05-grub.sh"
        "scripts/06-autologin.sh"
        "scripts/07-dashboard.sh"
        "scripts/08-prompt.sh"
        "scripts/09-harden.sh"
        "scripts/10-ai-stack.sh"
    )

    read -rp "  Select [1-10, or 0 to go back]: " choice
    if [[ "$choice" == "0" ]]; then
        show_main_menu
        return
    fi
    if [[ "$choice" =~ ^([1-9]|10)$ ]]; then
        local script="${SCRIPTS[$((choice-1))]}"
        step "Running ${script}"
        bash "$SCRIPT_DIR/$script"
        ok "Done: ${script}"
    else
        echo "  Invalid selection."
    fi
}

# ══════════════════════════════════════════════
# Workflow: Post-Install Setup
# ══════════════════════════════════════════════
run_post_install() {
    export MACHINE_NAME SETUP_USER PROMPT_EMOJI

    echo -e "\n${C}══════════════════════════════════════════════${R}"
    echo -e "${C}  Post-Install Setup${R}"
    echo -e "${C}══════════════════════════════════════════════${R}"
    echo ""
    echo -e "  ${G}1)${R} GitHub & SSH key setup"
    echo -e "  ${G}2)${R} Install Claude Code"
    echo -e "  ${G}3)${R} Configure dashboard"
    echo -e "  ${G}4)${R} Update MOTD art"
    echo -e "  ${G}5)${R} Fan curve setup"
    echo -e "  ${G}0)${R} Back to main menu"
    echo ""

    read -rp "  Select [1-5, or 0 to go back]: " choice
    case "$choice" in
        1) bash "$SCRIPT_DIR/post-install/github-ssh.sh" ;;
        2) bash "$SCRIPT_DIR/post-install/claude-code.sh" ;;
        3) bash "$SCRIPT_DIR/post-install/configure-dashboard.sh" ;;
        4) bash "$SCRIPT_DIR/post-install/update-motd-art.sh" ;;
        5) bash "$SCRIPT_DIR/post-install/fan-setup.sh" ;;
        0) show_main_menu; return ;;
        *) echo "  Invalid selection." ;;
    esac
}

# ══════════════════════════════════════════════
# Main Menu
# ══════════════════════════════════════════════
show_main_menu() {
    echo -e "\n${C}══════════════════════════════════════════════${R}"
    echo -e "${C}  LocoBase — ${MACHINE_NAME} ${PROMPT_EMOJI}${R}"
    echo -e "${C}══════════════════════════════════════════════${R}"
    echo ""
    echo -e "  ${G}1)${R} Fresh Install"
    echo -e "  ${G}2)${R} Fix Drift (re-run install)"
    echo -e "  ${G}3)${R} Full Reset"
    echo -e "  ${G}4)${R} Post-Install Setup"
    echo -e "  ${G}5)${R} Run Individual Script"
    echo -e "  ${G}6)${R} Rename Machine"
    echo ""

    read -rp "  Select [1-6]: " workflow
    case "$workflow" in
        1) run_install ;;
        2) run_install ;;
        3) run_reset ;;
        4) run_post_install ;;
        5) run_individual ;;
        6) run_rename ;;
        *) echo "  Invalid selection."; exit 1 ;;
    esac
}

# ══════════════════════════════════════════════
# Entry Point
# ══════════════════════════════════════════════

# Machine selection — show current or prompt for new
if [ -n "$MACHINE_NAME" ]; then
    echo ""
    echo -e "  Current machine: ${G}${MACHINE_NAME}${R} ${PROMPT_EMOJI}"
    read -rp "  Change machine? [y/N]: " change
    if [[ "$change" =~ ^[Yy] ]]; then
        select_machine
    fi
else
    select_machine
fi

show_main_menu
